name: scratchpad  

on: 
  push:   
    branches: [ main ]
 
jobs: 
  setup-containers:
    strategy:
      matrix:
          #os: [  'ol8','el8', 'el9', 'd10', 'd12', 'u18', 'u20'  ]
          os: [  'el9' ]
 
    runs-on: ubuntu-latest

    container: 
      #image: ghcr.io/perfsonar/unibuild/${{ matrix.os }}:latest
      #options: --privileged
      options: --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
      image: ghcr.io/perfsonar/docker-oneshot-builder/${{ matrix.os }}:latest
      volumes:
      - ${{ github.workspace }}:/build
        
    steps:
       - name: Check out Repo
         uses: actions/checkout@v3 

       - name: Build it
         run: make
         
