name: scratchpad  

on: 
  push:   
    branches: [ main ]
 
jobs:

  build:

    strategy:
      matrix:
        #os: [  'ol8','el8', 'el9', 'd10', 'd12', 'u18', 'u20'  ]
        os: [ 'el9' ]
 
    runs-on: ubuntu-latest
       
    steps:

      - name: Check out Repo
        uses: actions/checkout@v3

      - name: Build in Place with One-Shot Builder
        run: >
          curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build
              | sh -s - . '${{ matrix.os }}'
