name: scratchpad  

on: 
  push:   
    branches: [ main ]
 
jobs:

  build:

    strategy:
      matrix:
        # Working
        os: [ 'ol8', 'el9', 'u20', 'd11', 'd12', 'u22' ]

    runs-on: ubuntu-latest
       
    steps:

      - name: Check out Repo
        uses: actions/checkout@v4

      - name: Build in Place with One-Shot Builder
        run: >
          curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build \
              | sh -s - . '${{ matrix.os }}'
